//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicSession
    {
        public AcademicSession()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int AcademicSessionId { get; set; }
        public string AcademicYear { get; set; }
        public string Term { get; set; }
        public double FeesPayable { get; set; }
        public double FeesPaid { get; set; }
        public double FeesUnpaid { get; set; }
        public int NewStudentCount { get; set; }
        public bool IsInSession { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
