//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ParentId { get; set; }
        public string FatherTitle { get; set; }
        public string FatherFirstName { get; set; }
        public string FatherLastName { get; set; }
        public string FatherPhone { get; set; }
        public string MotherTitle { get; set; }
        public string MotherFirstName { get; set; }
        public string MotherLastName { get; set; }
        public string MotherPhone { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string ParentIdentificationNo { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
