//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClass
    {
        public StudentClass()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int StudentClassId { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual StudentClassBill StudentClassBill { get; set; }
    }
}
