//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClassBill
    {
        public int StudentClassBillId { get; set; }
        public double SchoolFees { get; set; }
        public double ExamFees { get; set; }
        public double LessonFees { get; set; }
        public double FirstAidFees { get; set; }
        public Nullable<double> ComputerFees { get; set; }
        public Nullable<double> MusicFees { get; set; }
        public double TextBookFees { get; set; }
        public double ExerciseBookFees { get; set; }
        public double FormFees { get; set; }
        public double UniformFees { get; set; }
        public double CardiganFees { get; set; }
        public double SportwearFees { get; set; }
        public double AnniversaryTshirtFees { get; set; }
        public double DevelopmentLevyFees { get; set; }
        public double Total { get; set; }
        public int StudentClass_StudentClassId { get; set; }
    
        public virtual StudentClass StudentClass { get; set; }
    }
}
