//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string TellerNo { get; set; }
        public int AccountAccountNo { get; set; }
        public int AcademicSessionAcademicSessionId { get; set; }
        public string TransactionIdentificationNo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AcademicSession AcademicSession { get; set; }
    }
}
